import { RawVector } from './types';
export declare class Vector {
    x: number;
    y: number;
    static readonly I: Vector;
    static readonly J: Vector;
    static readonly ZERO: Vector;
    constructor(x?: number, y?: number);
    get magnitude(): number;
    get quadrant(): 1 | 2 | 3 | 4;
    get reflexAngle(): number;
    add(v: Vector): Vector;
    subtract(v: Vector): Vector;
    multiply(s: number): Vector;
    divide(s: number): Vector;
    equals(v: Vector): boolean;
    closeTo(v: Vector): boolean;
    clone(): Vector;
    inv(): Vector;
    dot(v: Vector): number;
    scale(mag: number): Vector;
    scaleBy(fac: number): Vector;
    rotateBy(angle: number): Vector;
    dirToRight(v: Vector): boolean;
    angleTo(v: Vector): number;
    proj(v: Vector): Vector;
    distanceTo(v: Vector): number;
    toRaw(): RawVector;
    [Symbol.iterator](): Generator<number, void, unknown>;
    static fromRaw(raw: RawVector): Vector;
}
